---
#
# Ansible managed
#
repository:
  description: Install and configure [Bareos](https://www.bareos.com/) WebUI on your system.
  homepage: https://robertdebock.nl/
  topics: backup, bareos, infrastructure, linux, storage, system, tools, ansible, molecule, playbook
